#!/usr/bin/env python3
"""Regenerate committed filter coefficients and a validation report.

Usage: python scripts/design_filters.py [--check]

Writes src/noise_collector/dsp/coefficients/filters_<fs>.json and
docs/validation/filter-response.md. ``--check`` exits non-zero if the committed
coefficients differ from a fresh design by more than 1e-9 (reproducibility gate).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
from scipy import signal

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from noise_collector.dsp.design import design_lf_band, design_weighting  # noqa: E402
from noise_collector.dsp.reference import IEC_TABLE, analog_weighting_db, exact_frequency  # noqa: E402

RATES = (44100, 48000, 96000)
OUT = ROOT / "src/noise_collector/dsp/coefficients"
REPORT = ROOT / "docs/validation/filter-response.md"


def sos_hash(sos: list) -> str:
    return hashlib.sha256(json.dumps(sos, separators=(",", ":")).encode()).hexdigest()


def build(fs: int) -> dict:
    doc = {"sample_rate": fs, "filters": {}}
    for item in (design_weighting("A", fs), design_weighting("C", fs), design_lf_band(fs)):
        item["sha256"] = sos_hash(item["sos"])
        doc["filters"][item["kind"]] = item
    return doc


def report(docs: dict[int, dict]) -> str:
    lines = [
        "# Filter response validation",
        "",
        "Generated by `scripts/design_filters.py`. Digital response (`sosfreqz`) compared with the",
        "closed-form IEC 61672-1 analog weighting at exact base-10 one-third-octave frequencies.",
        "Design target: |error| <= 0.5 dB from 20 Hz to 10 kHz. Values above 10 kHz are reported only.",
        "This is a software response check, not standards conformance or instrument certification.",
        "",
    ]
    for fs, doc in docs.items():
        for kind in ("A", "C"):
            sos = np.array(doc["filters"][kind]["sos"])
            lines += [f"## {kind}-weighting @ {fs} Hz", "", f"sha256 `{doc['filters'][kind]['sha256']}`", "",
                      "| nominal Hz | exact Hz | digital dB | analog dB | error dB | IEC table dB |",
                      "|---:|---:|---:|---:|---:|---:|"]
            for nominal, vals in IEC_TABLE.items():
                f = exact_frequency(nominal)
                if f >= fs / 2:
                    continue
                _, h = signal.sosfreqz(sos, [f], fs=fs)
                d = 20 * np.log10(abs(h[0]))
                a = float(analog_weighting_db(kind, f))
                t = vals[0] if kind == "A" else vals[1]
                lines.append(f"| {nominal:g} | {f:.2f} | {d:.3f} | {a:.3f} | {d - a:+.3f} | {t:.1f} |")
            lines.append("")
        lf = doc["filters"]["LF"]
        sos = np.array(lf["sos"])
        lines += [f"## Low-frequency band @ {fs} Hz", "", f"{lf['method']}; sha256 `{lf['sha256']}`", "",
                  "| Hz | response dB |", "|---:|---:|"]
        for f in (5, 10, 16, 20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 500, 1000):
            _, h = signal.sosfreqz(sos, [f], fs=fs)
            lines.append(f"| {f:g} | {20 * np.log10(abs(h[0])):.2f} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    docs = {fs: build(fs) for fs in RATES}
    if args.check:
        bad = 0
        for fs, doc in docs.items():
            committed = json.loads((OUT / f"filters_{fs}.json").read_text())
            for kind, item in doc["filters"].items():
                diff = np.max(np.abs(np.array(item["sos"]) - np.array(committed["filters"][kind]["sos"])))
                if diff > 1e-9:
                    print(f"{fs} {kind}: max coefficient difference {diff:.3g}")
                    bad += 1
        return 1 if bad else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for fs, doc in docs.items():
        (OUT / f"filters_{fs}.json").write_text(json.dumps(doc, indent=1) + "\n")
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report(docs))
    print(f"wrote {len(docs)} coefficient files and {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
